SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `Agent`;
TRUNCATE TABLE `AgentAccount`;
TRUNCATE TABLE `Audio`;
TRUNCATE TABLE `Author`;
TRUNCATE TABLE `Book`;
TRUNCATE TABLE `BookCategory`;
TRUNCATE TABLE `cache`;
TRUNCATE TABLE `cache_locks`;
TRUNCATE TABLE `Category`;
TRUNCATE TABLE `EdunaConversation`;
TRUNCATE TABLE `EdunaFavorite`;
TRUNCATE TABLE `EdunaFeedback`;
TRUNCATE TABLE `EdunaPDF`;
TRUNCATE TABLE `EdunaPDFQuery`;
TRUNCATE TABLE `EdunaSession`;
TRUNCATE TABLE `failed_jobs`;
TRUNCATE TABLE `invitation_logs`;
TRUNCATE TABLE `jobs`;
TRUNCATE TABLE `job_batches`;
TRUNCATE TABLE `Like`;
TRUNCATE TABLE `Loand`;
TRUNCATE TABLE `NoLike`;
TRUNCATE TABLE `Notification`;
TRUNCATE TABLE `password_reset_tokens`;
TRUNCATE TABLE `personal_access_tokens`;
TRUNCATE TABLE `RefreshToken`;
TRUNCATE TABLE `Reservation`;
TRUNCATE TABLE `Sanction`;
TRUNCATE TABLE `sessions`;
TRUNCATE TABLE `StructBook`;
TRUNCATE TABLE `Structure`;
TRUNCATE TABLE `StructureNotifications`;
TRUNCATE TABLE `StructUser`;
TRUNCATE TABLE `struct_agent`;
TRUNCATE TABLE `Student`;
TRUNCATE TABLE `SubscribeBook`;
TRUNCATE TABLE `SubscribeCategory`;
TRUNCATE TABLE `User`;
TRUNCATE TABLE `UserNotificationRead`;
TRUNCATE TABLE `users`;
TRUNCATE TABLE `Version`;
TRUNCATE TABLE `View`;

SET FOREIGN_KEY_CHECKS = 1;
